### ISSUE TITLE
Generator not downloading edited avatar

### ISSUE THREAD

**Issue by hillonyechekwa** [RobertBroersma/bigheads#25]
After i edit the bighead to my taste, and i click on download SVG, it doesn't download what I edited. Instead it download the avatar on the hero of the landing page
![Screenshot from 2021-08-08 06-04-39](https://user-images.githubusercontent.com/46321192/128621477-9df4a966-915a-4d10-a89a-557054e40ea3.png)
 I think there's something wrong with the svg button

**Comment by RobertBroersma** [comment]
Hi @hillonyechekwa 

This is correct. The SVG download button depends on the `/svg` api handler, which I disabled due to high server costs. The API now points to a static .svg file so people using the API won't have empty images on their apps/websites all of a sudden.

Tbh I didn't really think about the download button, but I will look into a client-side download method which shouldn't be too hard.

Thanks for reporting!

**Comment by RobertBroersma** [comment]
Done! Download button now works client side.
